### ISSUE TITLE
コンテンツ

### ISSUE THREAD

**Issue by asonas** [kosendj/kosendj-bu.in#1]
## トップページ
- 直近のイベントの情報
- メンバーページのリンク
## 部員のページ

``` yaml
-
  name: asonas
  icon: http://example.com
  description: this is description
  activities:
    -
      comment: this is comment
      embed: '<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/145109495&amp;auto_play=false&amp;hide_related=false&amp;visual=true"></iframe>'
  services:
    -
      soundcloud: http://soundcloud.com/asonas
    -
      twitter: http://twitter.com/asonas
```

上のyamlでメンバーページを構成しようと思います。
こういう情報も載せたいとかあればレビューお願いします。
